services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    command: ["start-dev", "--import-realm"   ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - keycloak-network

  spring-boot-demo-api:
    build: ./
    container_name: spring-boot-demo-api
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge